version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    env_file: .env
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "always"

volumes:
  pgdata:
